### ISSUE TITLE
Which Linux distribution are you assuming?

### ISSUE THREAD

**Issue by ai2ys** [thorpelawrence/dng#1]
Which Linux distribution are you using for this project? Would you share the distribution name and the version?

Thank you.

**Comment by ai2ys** [comment]
I have an additional question. Is it possible to run the wrapper without having an UI (running the OS headless, e.g. in a docker container)?

**Comment by thorpelawrence** [comment]
Hi there, sorry as you can probably see I haven't documented this as I primarily wrote it for myself and didn't expect many others to find it.

Currently I've only packaged for and tested on Arch Linux. It might be possible to run completely headlessly but I haven't had a chance to test it unfortunately. In general if you provide some arguments rather than just running `dng` alone, it should process and run without loading the GUI.

Hope this helps

**Comment by ai2ys** [comment]
Thanks for your answer.
I created a docker image based on Arch Linux. Unfortunately, I have never used Arch Linux before, so it might be that I am doing it all wrong. 

In the dockerfile `. ./PKGBUILD && build && package` gets executed.

Running `dng --help` and `dng --version` works, but converting an image fails.

```
*** GL Error: DXGI_ERROR_UNSUPPORTED (hr=0x887a0004): CreateDXGIFactory1 failed ***
*** GL Error: CreateDXGIFactory1 failed ***
*** GL Error: MakeDirectXSystem failed ***
*** Error: Cannot init cloud download cache. ***
```

Do you have any idea?

**Comment by thorpelawrence** [comment]
> Thanks for your answer. I created a docker image based on Arch Linux. Unfortunately, I have never used Arch Linux before, so it might be that I am doing it all wrong.
> 
> In the dockerfile `. ./PKGBUILD && build && package` gets executed.
> 
> Running `dng --help` and `dng --version` works, but converting an image fails.
> 
> ```
> *** GL Error: DXGI_ERROR_UNSUPPORTED (hr=0x887a0004): CreateDXGIFactory1 failed ***
> *** GL Error: CreateDXGIFactory1 failed ***
> *** GL Error: MakeDirectXSystem failed ***
> *** Error: Cannot init cloud download cache. ***
> ```
> 
> Do you have any idea?

Interesting, the `DXGI_ERROR_UNSUPPORTED` looks like Wine is trying to use some DirectX features but they're unsupported by the container. I do think on the first run it shows a pop-up that it's creating the WINEPREFIX, so it might be that. One thing that might help is when setting up the Dockerfile you could pre-create the WINEPREFIX so it doesn't show that GUI. Something like this https://stackoverflow.com/a/25291298 maybe. The application will create it in `~/.local/share/dng/wine`.

**Comment by ai2ys** [comment]
I will check out your resources.

By the way I got distracted by the error messages, but the dng-converter outputs the DNG file. 😃

**Comment by thorpelawrence** [comment]
> I will check out your resources.
> 
> By the way I got distracted by the error messages, but the dng-converter outputs the DNG file. smiley

Ah, great! Yes the `Error: Cannot init cloud download cache.` seems to always be outputted, the others I'm not sure about.

**Comment by ai2ys** [comment]
> > Thanks for your answer. I created a docker image based on Arch Linux. Unfortunately, I have never used Arch Linux before, so it might be that I am doing it all wrong.
> > In the dockerfile `. ./PKGBUILD && build && package` gets executed.
> > Running `dng --help` and `dng --version` works, but converting an image fails.
> > ```
> > *** GL Error: DXGI_ERROR_UNSUPPORTED (hr=0x887a0004): CreateDXGIFactory1 failed ***
> > *** GL Error: CreateDXGIFactory1 failed ***
> > *** GL Error: MakeDirectXSystem failed ***
> > *** Error: Cannot init cloud download cache. ***
> > ```
> > 
> >   
> > Do you have any idea?
> 
> Interesting, the `DXGI_ERROR_UNSUPPORTED` looks like Wine is trying to use some DirectX features but they're unsupported by the container. I do think on the first run it shows a pop-up that it's creating the WINEPREFIX, so it might be that. One thing that might help is when setting up the Dockerfile you could pre-create the WINEPREFIX so it doesn't show that GUI. Something like this https://stackoverflow.com/a/25291298 maybe. The application will create it in `~/.local/share/dng/wine`.


Previous to your answer above I added the following and now the errors are gone, except for `*** Error: Cannot init cloud download cache. ***`.

```shell
pacman -Sy --noconfirm && pacman -S --noconfirm xorg-server-xvfb
export DISPLAY=":0"
Xvfb :0 -screen 0 1024x768x16 &
```

**Comment by thorpelawrence** [comment]
> > > Thanks for your answer. I created a docker image based on Arch Linux. Unfortunately, I have never used Arch Linux before, so it might be that I am doing it all wrong.
> > > In the dockerfile `. ./PKGBUILD && build && package` gets executed.
> > > Running `dng --help` and `dng --version` works, but converting an image fails.
> > > ```
> > > *** GL Error: DXGI_ERROR_UNSUPPORTED (hr=0x887a0004): CreateDXGIFactory1 failed ***
> > > *** GL Error: CreateDXGIFactory1 failed ***
> > > *** GL Error: MakeDirectXSystem failed ***
> > > *** Error: Cannot init cloud download cache. ***
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Do you have any idea?
> > 
> > 
> > Interesting, the `DXGI_ERROR_UNSUPPORTED` looks like Wine is trying to use some DirectX features but they're unsupported by the container. I do think on the first run it shows a pop-up that it's creating the WINEPREFIX, so it might be that. One thing that might help is when setting up the Dockerfile you could pre-create the WINEPREFIX so it doesn't show that GUI. Something like this https://stackoverflow.com/a/25291298 maybe. The application will create it in `~/.local/share/dng/wine`.
> 
> Previous to your answer above I added the following and now the errors are gone, except for `*** Error: Cannot init cloud download cache. ***`.
> 
> ```shell
> pacman -Sy --noconfirm && pacman -S --noconfirm xorg-server-xvfb
> export DISPLAY=":0"
> Xvfb :0 -screen 0 1024x768x16 &
> ```

Thanks for the info, I'll try to package a minimal Docker image using Debian or Alpine and put it in the repo.

**Comment by ai2ys** [comment]
I would be happy to share what I already created. I can provide it in a fork of your project.

**Comment by thorpelawrence** [comment]
> I would be happy to share what I already created. I can provide it in a fork of your project.

Thanks, I think I will still look to create one using a more standard distro so that it's more stable. I just used Arch on my workstation so that's what I originally designed it for, but in a docker image it makes sense to use a more stable base.

**Comment by ai2ys** [comment]
The dockerfile I created after forking your project: https://github.com/ai2ys/dng/tree/creating-dockerfile

**Comment by thorpelawrence** [comment]
Hi again, I've added a Dockerfile to the repo now

**Comment by ai2ys** [comment]
Thank you very much for the Dockerfile. Based on your Dockerfile I added one for Alpine. The resulting image is much smaller than the Debian image.
